export const formatTests = [
  {
    title: 'email format',
    schema: { format: 'email' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'idn-email format',
    schema: { format: 'idn-email' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'regex format',
    schema: { format: 'regex' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'ipv4 format',
    schema: { format: 'ipv4' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'ipv6 format',
    schema: { format: 'ipv6' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'idn-hostname format',
    schema: { format: 'idn-hostname' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'hostname format',
    schema: { format: 'hostname' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'date format',
    schema: { format: 'date' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
      { data: '1963-06-19' },
      { data: '2020-01-31' },
    ],
    invalidTestCases: [{ data: '2020-01-32' }],
  },
  {
    title: 'date-time format',
    schema: { format: 'date-time' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'time format',
    schema: { format: 'time' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'json-pointer format',
    schema: { format: 'json-pointer' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'relative-json-pointer format',
    schema: { format: 'relative-json-pointer' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'iri format',
    schema: { format: 'iri' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'iri-reference format',
    schema: { format: 'iri-reference' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'uri format',
    schema: { format: 'uri' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'uri-reference format',
    schema: { format: 'uri-reference' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
  {
    title: 'uri-template format',
    schema: { format: 'uri-template' },
    validTestCases: [
      { data: 12 },
      { data: 13.7 },
      { data: {} },
      { data: [] },
      { data: false },
      { data: null },
    ],
  },
];
